version: '3'
services:
  student_service:
    image: nginx
    restart: unless-stopped
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:UxQQYfaaSvjaiPQhTthwsNsijnQgQvtg@mongodb.railway.internal:27017
      DATABASE_NAME: test
      COLLECTION_NAME: students

    ports:
      - "8080:8080"

  mongo:
    restart: unless-stopped
    image: mongo:4
    ports:
      - "27017:27017"